### PR TITLE
Use rhc role instead of rhsm

### PR DESCRIPTION
**Pull request by rickgcv**

### CODE REVIEW

**Comment by rhmk** [comment]
This  role is deprecated and no longer valid. Please make the PR against https://github.com/sap-linuxlab/community.sap_operations/tree/main/roles/sap_rhsm

**Review by rhmk — COMMENTED** [review]
This is not required any more as this role is deprecated and should not be used at all any more. The new stuff needs to go here
https://github.com/sap-linuxlab/community.sap_operations/tree/main/roles/sap_rhsm

**Review by makentenza — APPROVED** [review]
LGTM

**Comment by rickgcv** [comment]
Thanks @makentenza @rhmk

**Pull request merged**
